version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - data:/mosquitto/data
      - log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

volumes:
  data:
  log:
