apiVersion: v1
kind: ConfigMap
metadata:
  name: hexa-posts-config
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.jdbc.Driver"
  MQTT_BROKER: "tcp://hexa-broker:1883"
---
apiVersion: v1
kind: Service
metadata:
  name: hexa-posts
  labels:
    app: posts
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: posts
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexa-posts
  labels:
    app: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: hexa-posts
          image: marloto/hexa-posts:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hexa-posts-config
            - configMapRef:
                name: hexa-database-config
            - secretRef:
                name: hexa-database-secrets
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: "${MYSQL_USER}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "${MYSQL_PASSWORD}"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://hexa-database:3306/${MYSQL_DATABASE}"
#          args: ["--spring.datasource.url=jdbc:mysql://db:3306/$(MYSQL_DATABASE)", "--spring.datasource.username=$(MYSQL_USER)", "--spring.datasource.password=$(MYSQL_PASSWORD)"]
#--spring.jpa.hibernate.ddl-auto=update --spring.datasource.url=jdbc:mysql://db:3306/${MYSQL_DATABASE} --spring.datasource.username=${MYSQL_USER} --spring.datasource.password=${MYSQL_PASSWORD} --spring.datasource.driver-class-name=com.mysql.jdbc.Driver --mqtt.broker=tcp://broker:1883
