apiVersion: v1
kind: PersistentVolume
metadata:
  name: hexa-database-volume
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/seb/Entwicklung/THI/Repositories/cnd-snippets/ws-2022/23-hexa-posts/database"
