spring.application.name: sesa-service-example
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/