version: "3.9"

services:
  app:
    build:
      context: .
    command: --spring.jpa.hibernate.ddl-auto=update --spring.datasource.url=jdbc:mysql://db:3306/${MYSQL_DB} --spring.datasource.username=${MYSQL_USER} --spring.datasource.password=${MYSQL_PASSWORD} --spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db-net

  db:
    image: mysql:5.7
    environment: # Konfigurationsmöglichkeiten im hub nachlesen
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      # - ./data:/var/lib/mysql # steht ebenfalls im hub, nicht das schönste
      - mysql-db:/var/lib/mysql
    networks:
      - db-net


volumes:
  mysql-db:

networks:
  db-net:
    driver: bridge 

