apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/seb/Entwicklung/THI/Repositories/cnd-snippets/ws-2022/19-kubernetes-volume/k8s/data"
