apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-demo
  labels:
    app: spring-java

spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-java
  template:
    metadata:
      labels:
        app: spring-java
    spec:
      containers:
        - name: spring-demo
          image: marloto/spring-java:1.1
          env:
            # Use secret in real usage
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/somedb
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.jdbc.Driver
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
