apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: mysql-local
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/seb/Entwicklung/THI/Repositories/sesa-ws-2021/exercise/spring-java/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: mysql-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi